# application: io-2017-timetrek
# version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bricks*
  script: qrparts.php

- url: /present*
  script: present.php
  
- url: /*
  script: main.php


